name: pdf_lab_pro
description: "All in One PDF Tools App"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.2.3

  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  go_router: ^17.0.0

  file_picker: ^10.3.7
  path_provider: ^2.1.5
  path: ^1.9.0
  mime: ^2.0.0


  printing: ^5.11.2
  pdf: ^3.11.3
  camera: ^0.11.3

  gallery_saver_plus: ^3.2.9

  image: ^4.1.7
  image_picker: ^1.1.3

  open_file: ^3.5.10
  share_plus: ^12.0.1

  permission_handler: ^12.0.1
  pdfrx: ^2.2.18
  file_selector: ^1.1.0



  # Storage
  shared_preferences: ^2.2.2  # Add this for settings

  # Utilities
  uuid: ^4.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  assets:
    #    - assets/icons/
    - assets/images/
    - assets/fonts/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/pdf_lab_pro.png
  android_12:
    color: "#ffffff"
    image: assets/images/pdf_lab_pro.png
  android: true
  ios: true
  web: false